name: Frontend Integration

on:
  pull_request:
    branches:
    - main
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    container:
      image: node:24.18.0
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Install Dependencies
        run: npm ci
      - name: Build Frontend
        run: npm run build
        
  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    container:
      image: node:24.18.0
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Install Dependencies
        run: npm ci
      - name: Run Linter
        run: npm run lint
