name: Integration Gateway

on:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]
jobs:
    run-frontend-integration:
        name: "Trigger Frontend Integration"
        uses: ./.github/workflows/frontend.yaml
    run-backend-integration:
        name: "Trigger Backend Integration"
        uses: ./.github/workflows/frontend.yaml           